unit Infrastructure.Database.Firebird;

interface

uses
  System.SysUtils,
  System.Classes,
  Core.Interfaces,
  FireDAC.Comp.Client,
  FireDAC.Stan.Intf,
  FireDAC.Stan.Option,
  FireDAC.Stan.Error,
  FireDAC.UI.Intf,
  FireDAC.Phys.Intf,
  FireDAC.Stan.Def,
  FireDAC.Stan.Pool,
  FireDAC.Stan.Async,
  FireDAC.Phys,
  FireDAC.Phys.FB,
  FireDAC.Phys.FBDef,
  FireDAC.VCLUI.Wait,
  Data.DB;

type
  TDbFirebirdManager = class(TInterfacedObject, IDatabaseManager)
  private
    FLogger: IAppLogger;
    class function GetPooledConnection: TFDConnection;
  public
    constructor Create(const ALogger: IAppLogger);
    class procedure InitializePool(const AConnectionString: string);
    class procedure DestroyPool;
    class procedure InitializeDatabase;

    procedure SaveData(const AJsonData: string);
    function GetDataAsJson: string;
  end;

const
  FB_POOL_DEF_NAME = 'MyDataSyncFBPool';

implementation

constructor TDbFirebirdManager.Create(const ALogger: IAppLogger);
begin
  inherited Create;
  FLogger := ALogger;
end;

class procedure TDbFirebirdManager.InitializePool(const AConnectionString: string);
var
  LParams: TStringList;
begin
  LParams := TStringList.Create;
  try
    LParams.Text := StringReplace(AConnectionString, ';', sLineBreak, [rfReplaceAll]);
    LParams.Add('Pooled=True');
    LParams.Add('POOL_MaximumItems=50');

    FDManager.AddConnectionDef(FB_POOL_DEF_NAME, 'FB', LParams);
    FDManager.Active := True;
  finally
    LParams.Free;
  end;
end;

class procedure TDbFirebirdManager.DestroyPool;
begin
  FDManager.Close;
end;

class function TDbFirebirdManager.GetPooledConnection: TFDConnection;
begin
  Result := TFDConnection.Create(nil);
  Result.ConnectionDefName := FB_POOL_DEF_NAME;
  Result.Open;
end;

class procedure TDbFirebirdManager.InitializeDatabase;
var
  LConn: TFDConnection;
begin
  LConn := GetPooledConnection;
  try
    LConn.ExecSQL('EXECUTE BLOCK AS BEGIN ' +
      '  if (not exists(select 1 from rdb$relations where rdb$relation_name = ''MYTABLE'')) then ' +
      '  execute statement ''CREATE TABLE MYTABLE (Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ' +
      '  Data BLOB SUB_TYPE TEXT NOT NULL, CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP)''; ' + 'END');
  finally
    LConn.Free;
  end;
end;

procedure TDbFirebirdManager.SaveData(const AJsonData: string);
var
  LConn: TFDConnection;
begin
  LConn := GetPooledConnection;
  try
    LConn.StartTransaction;
    try
      LConn.ExecSQL('INSERT INTO MYTABLE (Data) VALUES (:data)', [AJsonData]);
      LConn.Commit;
      FLogger.LogInfo('Zsynchronizowano dane (Firebird).');
    except
      on E: Exception do
      begin
        LConn.Rollback;
        FLogger.LogError('Błąd Firebird: ' + E.Message);
      end;
    end;
  finally
    LConn.Free;
  end;
end;

function TDbFirebirdManager.GetDataAsJson: string;
var
  LConn: TFDConnection;
  LQuery: TFDQuery;
begin
  Result := '';
  LConn := GetPooledConnection;
  try
    LQuery := TFDQuery.Create(nil);
    try
      LQuery.Connection := LConn;
      LQuery.SQL.Text := 'SELECT FIRST 1 Data FROM MYTABLE ORDER BY Id DESC';
      LQuery.Open;
      if not LQuery.IsEmpty then
        Result := LQuery.FieldByName('Data').AsString;
    finally
      LQuery.Free;
    end;
  finally
    LConn.Free;
  end;
end;

end.
